import { Rank } from "./Rank";
import { Suit } from "./Suit";

export const LennormandTarotReference = {
  1: { rank: Rank.Nine, suit: Suit.Hearts },
  2: { rank: Rank.Six, suit: Suit.Diamonds },
  3: { rank: Rank.Ten, suit: Suit.Spades },
  4: { rank: Rank.King, suit: Suit.Hearts },
  5: { rank: Rank.Seven, suit: Suit.Hearts },
  6: { rank: Rank.King, suit: Suit.Clubs },
  7: { rank: Rank.Queen, suit: Suit.Clubs },
  8: { rank: Rank.Nine, suit: Suit.Diamonds },
  9: { rank: Rank.Queen, suit: Suit.Spades },
  10: { rank: Rank.Jack, suit: Suit.Diamonds },
  11: { rank: Rank.Jack, suit: Suit.Clubs },
  12: { rank: Rank.Seven, suit: Suit.Diamonds },
  13: { rank: Rank.Jack, suit: Suit.Spades },
  14: { rank: Rank.Nine, suit: Suit.Clubs },
  15: { rank: Rank.Ten, suit: Suit.Clubs },
  16: { rank: Rank.Six, suit: Suit.Hearts },
  17: { rank: Rank.Queen, suit: Suit.Hearts },
  18: { rank: Rank.Ten, suit: Suit.Hearts },
  19: { rank: Rank.Six, suit: Suit.Spades },
  20: { rank: Rank.Eight, suit: Suit.Spades },
  21: { rank: Rank.Eight, suit: Suit.Clubs },
  22: { rank: Rank.Queen, suit: Suit.Diamonds },
  23: { rank: Rank.Seven, suit: Suit.Clubs },
  24: { rank: Rank.Jack, suit: Suit.Hearts },
  25: { rank: Rank.Ace, suit: Suit.Clubs },
  26: { rank: Rank.Ten, suit: Suit.Diamonds },
  27: { rank: Rank.Seven, suit: Suit.Spades },
  28: { rank: Rank.Ace, suit: Suit.Hearts },
  29: { rank: Rank.Ace, suit: Suit.Spades },
  30: { rank: Rank.King, suit: Suit.Spades },
  31: { rank: Rank.Ace, suit: Suit.Diamonds },
  32: { rank: Rank.Eight, suit: Suit.Hearts },
  33: { rank: Rank.Eight, suit: Suit.Diamonds },
  34: { rank: Rank.King, suit: Suit.Diamonds },
  35: { rank: Rank.Nine, suit: Suit.Spades },
  36: { rank: Rank.Six, suit: Suit.Clubs },
};
