export enum Trump {
  TheFool = "TheFool",
  TheMagician = "TheMagician",
  TheHighPriestess = "TheHighPriestess",
  TheEmpress = "TheEmpress",
  TheEmperor = "TheEmperor",
  TheHierophant = "TheHierophant",
  TheLovers = "TheLovers",
  TheChariot = "TheChariot",
  Strength = "Strength",
  TheHermit = "TheHermit",
  WheelOfFortune = "WheelOfFortune",
  Justice = "Justice",
  TheHangedMan = "TheHangedMan",
  Death = "Death",
  Temperance = "Temperance",
  TheDevil = "TheDevil",
  TheTower = "TheTower",
  TheStar = "TheStar",
  TheMoon = "TheMoon",
  TheSun = "TheSun",
  Judgement = "Judgement",
  TheWorld = "TheWorld",
}

export const ObjTrump = {
  TheFool: "The Fool",
  TheMagician: "The Magician",
  TheHighPriestess: "The High Priestess",
  TheEmpress: "The Empress",
  TheEmperor: "The Emperor",
  TheHierophant: "The Hierophant",
  TheLovers: "The Lovers",
  TheChariot: "The Chariot",
  Strength: "Strength",
  TheHermit: "The Hermit",
  WheelOfFortune: "Wheel of Fortune",
  Justice: "Justice",
  TheHangedMan: "The Hanged Man",
  Death: "Death",
  Temperance: "Temperance",
  TheDevil: "The Devil",
  TheTower: "The Tower",
  TheStar: "The Star",
  TheMoon: "The Moon",
  TheSun: "The Sun",
  Judgement: "Judgement",
  TheWorld: "The World",
};
